name: Commitlint

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate PR commits with commitlint
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlintrc.json
